In [3]:
import os
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

# exercise 1

### 1.1 Import the chipotle.tsv dataset

The dataset is available in the dataset folder as a tab separated value (.tsv) file. It is also available on [Kaggle](https://www.kaggle.com/datasets/navneethc/chipotle?select=chipotle.tsv).

### 1.2 Explore your data

In [4]:
#little help to start!
df = pd.read_csv(os.path.join('dataset','chipotle.tsv'), sep = '\t')
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

- Display the first entries

- Display the last 8 entries

- What is the number of observations in the dataset?

- What is the number of columns in the dataset?

- Print the name of all the columns

- Plot a histogram of "quantity" column

- Count the number of occurence of unique value in "quantity" column

- What is the type of the column item_price

- how many unique item_name are there?

### 1.3 Clean your data

- Delete the "choice_description" column

- Obtain the numeric value of the item_price and put it in a new column named "dollars"

### 1.4 Explore your data (pt. 2)

- what is the total revenue of the company?

- How many items were orderd in total?

- which is the most ordered item?

- sanity check: is the price of each item fixed?

- select the records of the dataset in which the order consists in just a single (quantity = 1) Steak Burrito. How many records? What is the price distribution?

- what is the average revenue amount per order?

In [5]:
# TODO

# exercise 2
- Practice with pandas and matplotlib:
    - load the [covid19-healthy-diet-dataset](https://www.kaggle.com/datasets/mariaren/covid19-healthy-diet-dataset): it contains some stats related to covid19 and diet for each country.
    - add domain information: create a new column with the continent (plenty of python libraries out there)
        - for example, install `pycountry_convert` and ...
            - obtain the country_code from the country_name with `pycountry_convert.country_name_to_country_alpha2`
            - obtain the continent_code from the country_code with `pycountry_convert.country_alpha2_to_continent_code`

    - use pandas and plotting utilities to explore the data, e.g.:
        - Which continents have the highest ratio reported for Covid19 deaths?
        - Which is the state with the highest rate of death?
        - Compare the distribution of Deaths rates among European and North American countries.

In [4]:
# little help:
import pandas as pd
import os
df = pd.read_csv(os.path.join('dataset','healthCovid19.csv'),index_col = 0)
df.head(10)

,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,Miscellaneous,...,Vegetable Oils,Vegetables,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.0,21.6397,6.2224,0.0,8.0353,0.6859,0.0327,0.4246,6.1244,0.0163,...,17.0831,0.3593,4.5,29.8,0.142134,0.006186,0.123374,0.012574,38928000.0,%
Albania,0.0,32.0002,3.4172,0.0,2.6734,1.6448,0.1445,0.6418,8.7428,0.0170,...,9.2443,0.6503,22.3,6.2,2.967301,0.050951,1.792636,1.123714,2838000.0,%
Algeria,0.0,14.4175,0.8972,0.0,4.2035,1.2171,0.2008,0.5772,3.8961,0.0439,...,27.3606,0.5145,26.6,3.9,0.244897,0.006558,0.167572,0.070767,44357000.0,%
Angola,0.0,15.3041,1.3130,0.0,6.5545,0.1539,1.4155,0.3488,11.0268,0.0308,...,22.4638,0.1231,6.8,25,0.061687,0.001461,0.056808,0.003419,32522000.0,%
Antigua and Barbuda,0.0,27.7033,4.6686,0.0,3.2153,0.3872,1.5263,1.2177,14.3202,0.0898,...,14.4436,0.2469,19.1,NaN,0.293878,0.007143,0.190816,0.095918,98000.0,%
Argentina,0.0,30.3572,3.3076,0.0,1.3316,1.5706,0.1664,0.2091,19.2693,0.0000,...,17.3147,0.1878,28.5,4.6,4.356147,0.108227,3.905192,0.342729,45377000.0,%
Armenia,0.0,29.6642,6.2619,0.0,2.5068,1.6196,0.2218,0.5468,10.8165,0.0361,...,12.8127,0.8717,20.9,4.3,5.681225,0.105345,5.398410,0.177470,2956000.0,%
Australia,0.0,24.1099,4.6030,0.0,0.9908,0.7017,0.4515,0.4028,11.6002,0.0520,...,20.3612,0.2144,30.4,<2.5,0.112025,0.003530,0.101289,0.007207,25754000.0,%
Austria,0.0,27.8268,12.8517,0.0,1.2297,1.2147,0.4259,0.2249,8.1099,0.0000,...,17.9323,0.2039,21.9,<2.5,4.739982,0.089679,4.496870,0.153433,8914000.0,%
Azerbaijan,0.0,32.1198,7.7987,0.0,5.4481,2.0197,0.2122,0.5940,11.9993,0.0170,...,7.1538,0.6534,19.9,<2.5,2.285536,0.031223,2.225574,0.028740,10108000.0,%

In [7]:
# TODO